---
- hosts: all
  tasks:

  # - name: Check Chocolatey is installed
  #   win_shell: if ($env:ChocolateyInstall){return $true} else {return $false}
  #   register: chocolatelyInstalled

  # - name: Install Chocolatey
  #   win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  #   when: not chocolatelyInstalled.stdout_lines

  - name: Install package dependencies
    win_chocolatey:
      name:
       - chocolatey-core.extension
       - chocolatey-windowsupdate.extension
      state: present

  - name: Install VS Code and PowerShell Preview
    win_chocolatey:
      name:
      - vscode.install
      - powershell-preview
      state: present

