---
- hosts: all
  gather_facts: false
  tasks:

  - name: Test API
    uri:
      url: "https://httpbin.org/anything"
      method: POST
      #user: "test"
      #password: "Passwo"
      #validate_certs: no
      force_basic_auth: yes
      return_content: yes
      status_code:
      - 200
      body:
        testdata : true
      body_format: json
    register: apiStatusOutput

  # - name: The following IPs were found
  #   debug:
  #     msg: "IPs are: {{ apiStatusOutput.json.origin }}"

  # - name: fail on error
  #   fail:
  #     msg: "Failing the job, errors in the return data: {{ apiStatusOutput.json.origin }}"
  #   when: apiStatusOutput.json.origin != "51.145.117.171, 51.145.117.171" #== for testing purposes