---
- hosts: all
  gather_facts: false
  tasks:

  - name: Test API
    uri:
      url: "https://httpbin.org/ip"
      method: GET
      #user: "test"
      #password: "Passwo"
      #validate_certs: no
      force_basic_auth: yes
      return_content: yes
      status_code:
      - 200
    register: apiStatusOutput

  - name: The following IPs were found
    debug:
      msg: "IPs are: {{ apiStatusOutput.json.origin }}"

  # - name: fail on error
  #   fail:
  #     msg: "Failing the job, errors in the return data: {{ apiStatusOutput.json.origin }}"
  #   when: (apiStatusOutput.json.origin | length > 0 ) #== for testing purposes