---
- hosts: all
  tasks:

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test_output1.ps1"
      dest: C:\Temp\test_output1.ps1

  - name: Run a script
    win_shell: C:\temp\test_output1.ps1
    register: result1

  - name: Process win_shell output
    set_fact:
      vms: "{{ result1.stdout | regex_findall('(?<=VM: )(.*)') }}"