---
- hosts: all
  tasks:

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test_output2.ps1"
      dest: C:\Temp\test_output2.ps1

  - name: Run a script
    win_shell: C:\temp\test_output2.ps1
    register: result2

  - name: Process win_shell output
    set_fact:
      vm: "{{ result2.stdout | from_json }}"

  - name: Debug VM properties
    debug:
      msg: VM {{ vm.name }} has IP Address {{ vm.ipAddress }}


  - name: Debug vm length
    debug:
      msg: "vm Number_of_elements: {{ vm |length }} "

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test_output3.ps1"
      dest: C:\Temp\test_output3.ps1

  - name: Run a script
    win_shell: C:\temp\test_output3.ps1
    register: result3

  - name: Process win_shell output
    set_fact:
      vm2: "{{ result3.stdout | from_json }}"

  - name: Debug vm2 length
    debug:
      msg: "vm2 Number_of_elements: {{ vm2 |length }} "

  # - name: Debug VM properties
  #   debug:
  #     msg: VM {{ vm.name }} has IP Address {{ vm.ipAddress }}