---
- hosts: all
  tasks:

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test_output2.ps1"
      dest: C:\Temp\test_output2.ps1

  - name: Run a script
    win_shell: C:\temp\test_output2.ps1
    register: result2

  - name: Process win_shell output
    set_fact:
      vm: "{{ result2.stdout | from_json }}"

  - name: Debug VM properties
    debug:
      msg: VM {{ vm.name }} has IP Address {{ vm.ipAddress }}


  - name: Debug vm type
    debug:
      msg: "vm type: {{ vm | type_debug }} "

  - name: Debug vm dict
    debug:
      msg: "Display this when dict"
    when:  "{{ vm | type_debug }} == dict"

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test_output3.ps1"
      dest: C:\Temp\test_output3.ps1

  - name: Run a script
    win_shell: C:\temp\test_output3.ps1
    register: result3

  - name: Process win_shell output
    set_fact:
      vm2: "{{ result3.stdout | from_json }}"

  - name: Debug vm2 type
    debug:
      msg: "vm2 type: {{ vm2 | type_debug }} "

  - name: Debug vm dict
    debug:
      msg: "Display this when dict"
    when:  "{{ vm2 | type_debug }} == dict"

  # - name: Debug VM properties
  #   debug:
  #     msg: VM {{ vm.name }} has IP Address {{ vm.ipAddress }}