---
- hosts: all
  tasks:

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test_output2.ps1"
      dest: C:\Temp\test_output2.ps1

  - name: Run a script
    win_shell: C:\temp\test_output2.ps1
    register: result2

  - name: Process win_shell output
    set_fact:
      vm: "{{ result2.stdout | from_json }}"

  - name: Debug VM properties
    debug:
      msg: VM {{ vm.name }} has IP Address {{ vm.ipAddress }}


  - name: Set vm type
    set_fact:
      vm_type: "{{ vm | type_debug }}"

  - name: Debug vm dict
    debug:
      msg: "Display this when dict"
    when:  vm_type == 'list'

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test_output3.ps1"
      dest: C:\Temp\test_output3.ps1

  - name: Run a script
    win_shell: C:\temp\test_output3.ps1
    register: result3

  - name: Process win_shell output
    set_fact:
      vm2: "{{ result3.stdout | from_json }}"

  - name: Set vm2 type
    set_fact:
      vm2_type: "{{ vm2 | type_debug }}"

  - name: Debug vm dict
    debug:
      msg: "Display this when list"
    when:  vm2_type == 'list'

  # - name: Debug VM properties
  #   debug:
  #     msg: VM {{ vm.name }} has IP Address {{ vm.ipAddress }}