---
- hosts: all
  tasks:

  - name: Create new local account
    win_user:
      name: "{{ local_account_username }}"
      fullname: "{{ local_account_fullname }}"
      password: "{{ local_account_password }}"
      state: present
      groups:
        - Administrators

  - name: Ensure test_user02 does not exist
    win_user:
      name: test_user02
      state: absent
