---
- hosts: all
  tasks:

  - name: Create new local account
    win_user:
      name: "{{ local_account_username }}"
      password: "{{ local_account_password }}"
      state: present
      groups:
        - Users
