---
- hosts: all
  tasks:

  # - name: Get-ChildItem via command module
  #   command: pwsh-preview -Command "try {Get-ChildItem test -ErrorAction SilentlyContinue} catch {exit 0}"
  #   register: childItemData

  # - name: Get-Error via command module
  #   command: pwsh-preview -Command "Get-Error"
  #   register: errorData

  # - name: Process output
  #   set_fact:
  #     processes: "{{ processData.stdout | from_json }}"


  - name: Run a script
    shell: "{{ playbook_dir }}/files/test_output4.ps1"
    args:
      executable: /usr/bin/pwsh-preview
    register: result1

  - name: Process output
    set_fact:
      errorDetail: "{{ result1.stdout | from_json }}"

  - debug:
      msg: "Error Category: {{ errorDetail.Category }}, Error Activity: {{ errorDetail.Activity }}, Error Reason: {{ errorDetail.Reason }} for Target {{ errorDetail.TargetName }}"

  - name: Invoke-RestMethod via shell module
    shell: Invoke-RestMethod -Uri 'https://httpbin.org/get' | ConvertTo-Json
    args:
      executable: /usr/bin/pwsh-preview
    register: apiRequest

  - name: Process output
    set_fact:
      apiOutput: "{{ apiRequest.stdout | from_json }}"

  - debug:
      msg: "The User-Agent used to make the API request was {{ apiOutput.headers['User-Agent'] }}"
