---
- hosts: all
  tasks:

  - name: Get-ChildItem via command module
    command: pwsh-preview -Command "Get-ChildItem test -ErrorAction SilentlyContinue"
    register: childItemData

  - name: Get-Error via command module
    command: pwsh-preview -Command "Get-Error"
    register: errorData

  # - name: Process output
  #   set_fact:
  #     processes: "{{ processData.stdout | from_json }}"

  - debug:
      msg: "Errordata: {{ errorData }}"

  - name: Invoke-RestMethod via shell module
    shell: Invoke-RestMethod -Uri 'https://httpbin.org/get' | ConvertTo-Json
    args:
      executable: /usr/bin/pwsh-preview
    register: apiRequest

  - name: Process output
    set_fact:
      apiOutput: "{{ apiRequest.stdout | from_json }}"

  - debug:
      msg: "The User-Agent used to make the API request was {{ apiOutput.headers['User-Agent'] }}"
