---
- hosts: all
  gather_facts: False
  tasks:

  - name: Run a pwsh command
    shell: Get-Process | ConvertTo-Json
    args:
      executable: /usr/bin/pwsh
    register: result

  - name: Process win_shell output
    set_fact:
      processes: "{{ result.stdout | from_json }}"

  - name: Debug process properties
    debug:
      msg: Process {{ item.Name }} has SessionId {{ item.SessionId }}
    loop: processes