---
- hosts: all
  gather_facts: True
  tasks:

  - name: Run a pwsh command
    shell: Get-Process | ConvertTo-Json
    args:
      executable: /usr/bin/pwsh
    register: result

  - name: Process win_shell output
    set_fact:
      processes: "{{ result.stdout | from_json }}"

  - name: Search for data
    set_fact:
      cron_process: "{{ processes | selectattr('Name', 'equalto', 'cron') | list }}"

  - name: Debug process properties
    debug:
      msg: Process {{ cron_process.Name }} has SessionId {{ cron_process.SessionId }} and a VirtualMemorySize of {{ cron_process.VirtualMemorySize}}
