---
- hosts: 10.0.3.4
  tasks:
  - name: Powershell | Install Required Powershell Modules
    win_psmodule: name={{ item }} state=present
    with_items:
      - xSCVMM

  - name: Install SCVMM Console
    win_dsc:
      resource_name: xSCVMMManagementServerSetup
      Ensure: "Present"
      SourcePath: 'E:\'
      SourceFolder: "SCVMM"
      SetupCredential_username: "svc_ansible"
      SetupCredential_password: "P@ssword!"
      vmmService_username: "SPRINGFIELD\\svc_vmm"
      vmmService_password: "P@ssword!"
      sqlService_username: "SPRINGFIELD\\sql_svc"
      sqlService_password: "P@ssword!"
      SqlMachineName: "scvmm01"
      SqlInstanceName: "MSSQLSERVER"
      CompanyName: "Test Inc"
      CreateNewSqlDatabase: 1
      SqlDatabaseName: VirtualManagerDB
      CreateNewLibraryShare: 1
      LibrarySharePath: "E:\\MSSCVMMLibrary"
      LibraryShareName: "MSSCVMMLibrary"
      SQMOptIn: 1
      MUOptIn: 1




#RemoteDatabaseImpersonation = 1


#SqlMachineName=$($env:COMPUTERNAME)
# SqlDBAdminName=$VMMServiceUsername
# SqlDBAdminDomain=$VMMServiceDomain
# SqlDBAdminPassword=$VmmServiceUserPassword
#VmmServiceLocalAccount=1







  # - name: Install SCVMM Console
  #   win_dsc:
  #     resource_name: xSCVMMConsoleSetup
  #     Ensure: "Present"
  #     SourcePath: "E:\\"
  #     SourceFolder: "SCVMM"
  #     SetupCredential_username: "svc_ansible"
  #     SetupCredential_password: "P@ssword!"