---
- hosts: 10.0.3.4
  tasks:
  - name: Powershell | Install Required Powershell Modules
    win_psmodule: name={{ item }} state=present
    with_items:
      - xSCVMM

  - name: Install SCVMM Console
    win_dsc:
      resource_name: xSCVMMConsoleSetup
      Ensure: "Present"
      SourcePath: "E:\\"
      SourceFolder: "SCVMM"
      SetupCredential_username: "svc_ansible"
      SetupCredential_password: "P@ssword!"