---
- hosts: all
  tasks:
  - name: Create scheduled task
    win_scheduled_task:
      name: scvmm_test
      description: install scvmm
      actions:
      - path: C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe
        arguments: -File E:\Install-SCVMM.ps1 -VmmServiceDomain Springfield -VmmServiceUserName svc_vmm -VmmServiceUserPassword P@ssword!
      username: SPRINGFIELD\jmedd
      password: P@ssword!
      run_level: highest
      logon_type: password
      state: present
      enabled: yes


  - name: Run scheduled task
    win_shell: E:\Invoke-ScheduledTask.ps1