---
- hosts: 10.0.3.4
  tasks:
  - name: Powershell | Install Required Powershell Modules
    win_psmodule: name={{ item }} state=present
    with_items:
      - SQLServerDsc
      - StorageDsc
      - ServerManager
      - dbatools
      - xNetworking

  - name: Install SQL Server
    win_dsc:
      resource_name: SQLSetup
      Action: Install
      UpdateEnabled: True
      SourcePath: "E:\\Temp\\SQL"
      InstanceName: "MSSQLSERVER"
      InstallSharedDir: "C:\\Program Files\\Microsoft SQL Server"
      InstallSharedwowDir: "C:\\Program Files (x86)\\Microsoft SQL Server"
      InstanceDir: "C:\\Program Files\\Microsoft SQL Server"
      SQLUserDBDir: "C:\\Program Files\\Microsoft SQL Server\\MSSQL13.MSSQLSERVER\\MSSQL\\Data"
      SQLUserDBLogDir: "C:\\Program Files\\Microsoft SQL Server\\MSSQL13.MSSQLSERVER\\MSSQL\\Data"
      SQLTempDBDir: "C:\\Program Files\\Microsoft SQL Server\\MSSQL13.MSSQLSERVER\\MSSQL\\Data"
      SQLTempDBLogDir: "C:\\Program Files\\Microsoft SQL Server\\MSSQL13.MSSQLSERVER\\MSSQL\\Data"
      Features: "SQLENGINE,AS"
      SQLCollation: "SQL_Latin1_General_CP1_CI_AS"
      # BrowserSvcStartupType: "{{ mssql_browsersvc_mode }}"
      # SuppressReboot: "{{ mssql_suppress_reboot }}"
      SQLSysAdminAccounts: "SPRINGFIELD\\sql_admins"
      PsDscRunAsCredential_username: 'svc_ansible'
      PsDscRunAsCredential_password: 'Password123'
    no_log: true
    tags: install_sql

  - name: Configure the MSSQLSERVERAGENT Service
    win_service:
      name: sqlserveragent
      state: started
      username: "SPRINGFIELD\\sql_service"
      password: "Password123"
    tags: install_sql