---
- hosts: 10.0.3.4
  tasks:
  - name: Powershell | Install Required Powershell Modules
    win_psmodule: name={{ item }} state=present
    with_items:
      - SQLServerDsc
      - StorageDsc
      - ServerManager
      - dbatools
      - xNetworking


# - name: Install SQL Server
#   win_dsc:
#     resource_name: SQLSetup
#     Action: Install
#     UpdateEnabled: True
#     SourcePath: "{{ mssql_installation_path }}\\Media"
#     InstanceName: "{{ mssql_instance_name }}"
#     InstallSharedDir: "{{ mssql_installshared_path }}"
#     InstallSharedwowDir: "{{ mssql_installsharedwow_path }}"
#     InstanceDir: "{{ mssql_instance_path }}"
#     SQLUserDBDir: "{{ mssql_sqluserdata_path }}"
#     SQLUserDBLogDir: "{{ mssql_sqluserlog_path }}"
#     SQLTempDBDir: "{{ mssql_sqltempDB_path }}"
#     SQLTempDBLogDir: "{{ mssql_sqltempDBlog_path }}"
#     Features: "{{ mssql_features }}"
#     SQLCollation: "{{ mssql_collation }}"
#     BrowserSvcStartupType: "{{ mssql_browsersvc_mode }}"
#     SuppressReboot: "{{ mssql_suppress_reboot }}"
#     SQLSysAdminAccounts: "{{ mssql_sysadmin_accounts }}"
#     PsDscRunAsCredential_username: '{{ ansible_user }}'
#     PsDscRunAsCredential_password: '{{ ansible_password }}'
#   no_log: true
#   tags: install_sql

# - name: Configure the MSSQLSERVERAGENT Service
#   win_service:
#     name: sqlserveragent
#     state: started
#     username: "{{ mssql_agentsvc_account }}"
#     password: "{{ mssql_agentsvc_account_pass }}"
#   tags: install_sql