---
- hosts: all
  tasks:

  - name: Check if a service is installed
    win_service:
      name: SNMPTRAP
    register: service_info

  # - name: Test command on local host
  #   wait_for: host=www.google.com port=80
  #   delegate_to: awx

  - name: Test shell command
    shell: hostname
    delegate_to: localhost

  - name: Test URI
    uri:
      url: https://jsonplaceholder.typicode.com/todos/1
      return_content: yes
    register: this
    delegate_to: localhost

  - name: Configure the SNMPTRAP Service
    win_service:
      name: SNMPTRAP
      state: started
      start_mode: auto