---
- hosts: all
  tasks:

  - name: Check if a service is installed
    win_service:
      name: SNMPTRAP
    register: service_info

  - name: Run a script
    shell: "{{ playbook_dir }}/files/test_output4.ps1"
    args:
      executable: /usr/bin/pwsh
    register: result1
    delegate_to: localhost

  - name: Configure the SNMPTRAP Service
    win_service:
      name: SNMPTRAP
      state: started
      start_mode: auto