---
- hosts: localhost
  tasks:
  - name: Running API
    uri:
      url: https://reqres.in/api/users?page=2
      method: GET
      return_content: yes
    register: user_list

  - name: App Details
    debug: var=user_list

  - set_fact:
      user_avatar: "{{ lookup('template', './test.yml.j2') }}"

  - name: User Avatar
    debug: var=user_avatar