---
- hosts: localhost
  tasks:
  - name: Create Token
    uri:
      url: https://api.mgmt.cloud.vmware.com/iaas/login
      method: POST
      return_content: yes
      body:
        refreshToken: 78b07539-89a5-4c4a-885d-a444bb08e4cb
      body_format: json
    register: create_token

  - set_fact:
      token: "{{ 'Bearer ' + create_token.json.token }}"

  - name: Log token
    debug: var=token

  - name: Get Projects
    uri:
      url: https://api.mgmt.cloud.vmware.com/iaas/projects
      method: GET
      return_content: yes
      headers:
        Authorization: "{{ token }}"
    register: projects


  - name: Log projects
    debug: var=projects.json.content

  - set_fact:
      project_exists: "{{ lookup('template', './testCAS.yml.j2') }}"

  - name: Log result
    debug: var=project_exists

  - name: Create Project
    uri:
      url: https://api.mgmt.cloud.vmware.com/iaas/projects
      method: POST
      return_content: yes
      headers:
        Authorization: "{{ token }}"
      body: "{{ lookup('file','project.json') }}"
      body_format: json
    register: create_project
    when: not project_exists

  - name: Log New Project
    debug: var=create_project
    when: not project_exists