---
- hosts: localhost
  tasks:
  - name: Get Projects
    uri:
      url: https://api.mgmt.cloud.vmware.com/iaas/projects
      method: GET
      return_content: yes
      headers:
        Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InNpZ25pbmdfMiJ9.eyJzdWIiOiJ2bXdhcmVpZDoxNWU5YTU4OC1iZmNmLTRiMmItYTIxNS04MzkyMDAxZjNmZGMiLCJhenAiOiJjc3BfcHJkX2dhel9pbnRlcm5hbF9jbGllbnRfaWQiLCJkb21haW4iOiJ2bXdhcmVpZCIsImNvbnRleHQiOiIzN2YwMzkwOS1kNjYwLTQwNDItOTQ0My0wMWE5NTA0MTliM2UiLCJpc3MiOiJodHRwczovL2dhei5jc3AtdmlkbS1wcm9kLmNvbSIsInBlcm1zIjpbImNzcDpvcmdfbWVtYmVyIiwiZXh0ZXJuYWwvWnk5MjRtRTNkd24yQVN5VlpSME5uN2x1cGVBXy9hdXRvbWF0aW9uc2VydmljZTpjbG91ZF9hZG1pbiIsImV4dGVybmFsL3VsdnF0TjQxNDFiZUNUMm9PbmJqLXdsa3pHZ18vQ29kZVN0cmVhbTphZG1pbmlzdHJhdG9yIl0sImNvbnRleHRfbmFtZSI6IjdkMjMxYjNhLTkzM2QtNDViNy05OGMyLTk0OTdmNzRmNzAwOSIsImV4cCI6MTU1MTk3NTEyOCwiaWF0IjoxNTUxOTczMzI4LCJqdGkiOiI0MmU2Mzg4ZC03NTNmLTQ1MDQtYjcyMS0yMzYzOWM0MDM3M2UiLCJhY2N0Ijoiam9uYXRoYW4ubWVkZCU0MGF0b3MubmV0QHZtd2FyZWlkIiwidXNlcm5hbWUiOiJqb25hdGhhbi5tZWRkQGF0b3MubmV0In0.LZkWAvFu7oZKtZBVBAZyJ_xR11kGEdybvjC0V66S8gG4PHgtsmQheJTvZnwgNXM5MDrIaTim1hyfy1LriB2dzM2kdaxytt5AMf45T2QLx0n3ICIUgWjmCKZ7NOV_RvlDHj4zP6pJQR50J7vvIgFR5uv-b5ZIQheR1ibJ4M4uILIALQKk6yZHB1unJA39CHGFSBFepHVcht0E_UnxA5JzPWnYt5j08nYDHdsvmZYnmLKZpQse1bRFeVXIEO3cXBSd9fSiqoan43u1FxTbRtr1yyp-_KPu-QlrFWWe9KEHYn8LLb9a6eK1l51De_DGErgj2G-3nW9wvbq56iZij7YB2Q"
    register: projects


  - name: Log projects
    debug: var=projects.json.content