---
- hosts: all
  tasks:
  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test-output.ps1"
      dest: C:\Temp\test-output.ps1

  - name: Run a script
    win_shell: C:\Temp\test-output.ps1
    register: result
  - set_fact:
        myvalue: "{{ result.stdout | regex_findall('(?<=VM: )(.*)') }}"
  - debug:
      var: myvalue

  # - debug: var=result.stdout_lines

  # - name: wait for vm to respond
  #   wait_for:
  #     host: "{{ VM_StaticIPAddress.split('/')[0] }}"
  #     port: 5985
  #     delay: 300
  #     timeout: 600
  #     connect_timeout: 30
  #   delegate_to: localhost