---
- hosts: all
  tasks:
  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test-output.ps1"
      dest: C:\Temp\test-output.ps1

  - name: Run a script
    win_shell: C:\Temp\test-output.ps1
    register: result
  - set_fact:
        vms: "{{ result.stdout | regex_findall('(?<=VM: )(.*)') }}"
  - debug:
      var: vms

  # - debug: var=result.stdout_lines

  - name: wait for vm to respond
    wait_for:
      host: "{{ item }}"
      port: 5985
      delay: 3
      timeout: 600
      connect_timeout: 5
    delegate_to: localhost
    loop: "{{  vms  }}"